# AWE-FF|

In [3]:
from AnonymousWalkKernel import GraphKernel
from AnonymousWalkKernel import AnonymousWalks
import numpy as np
from AnonymousWalkKernel import Evaluation
# activate awe


In [12]:
# Data load

dataname = 'Disc6'

gk = GraphKernel()
gk.read_graphs(folder = 'Datasets/' + dataname + '/', ext = 'graphml')

y = []
with open('Datasets/' + dataname +'/labels.txt') as f:
    for line in f:
        y.extend(list(map(int, line.strip().split())))
y = np.array(y)
print('Number of graphs: {}'.format(len(gk.graphs)))

Number of graphs: 120


In [15]:
length = 6
gk.embed_graphs(steps = length, keep_last=True)

E = gk.embeddings
print('Embeddings matrix of shape: {} x {}'.format(E.shape[0], E.shape[1]))

Using exact method to get graph embeddings
Dimension size: 203
Processing 0 graph
Processing 10 graph
Processing 20 graph
Processing 30 graph
Processing 40 graph
Processing 50 graph
Processing 60 graph
Processing 70 graph
Processing 80 graph
Processing 90 graph
Processing 100 graph
Processing 110 graph
Embeddings matrix of shape: 120 x 203


In [16]:
gk.embeddings = E
gk.kernel_matrix(kernel_method='rbf', build_embeddings=False)
K = gk.K
print('Kernel matrix has shape: {} x {}'.format(K.shape[0], K.shape[1]))

Kernel matrix has shape: 120 x 120


In [17]:
k = 10
ev = Evaluation(matrix = K, labels = y, verbose = True)
accuracies = ev.evaluate(k=k)
print('Performed {}-fold validation and scored {:.2f}% mean accuracy in graph classification'.format(k, 100*np.mean(accuracies)))

[3 3 4 3 4 3 3 4 4 4 4 4]
Scored 0.0 on validation and 0.0 on test with C = 0.001
[3 3 3 3 3 3 3 3 3 3 3 3]
Scored 0.0 on validation and 0.0 on test with C = 0.001
[0 0 0 0 0 0 0 0 0 0 0 0]
Scored 0.0 on validation and 0.0 on test with C = 0.001
[2 2 2 2 2 2 2 2 2 2 2 2]
Scored 0.3333333333333333 on validation and 0.0 on test with C = 0.001
[2 2 2 2 2 2 2 2 2 2 2 2]
Scored 0.25 on validation and 0.0 on test with C = 0.001
[1 7 7 7 0 6 6 1 1 6 3 1]
Scored 0.0 on validation and 0.4166666666666667 on test with C = 0.001
[3 3 3 3 3 3 3 3 3 3 3 3]
Scored 0.0 on validation and 0.0 on test with C = 0.001
[1 1 1 1 1 1 1 1 1 1 1 1]
Scored 0.3333333333333333 on validation and 0.0 on test with C = 0.001
[6 6 5 6 6 6 5 6 6 6 6 5]
Scored 0.16666666666666666 on validation and 0.0 on test with C = 0.001
[7 7 7 7 7 7 7 7 7 7 7 7]
Scored 0.08333333333333333 on validation and 0.0 on test with C = 0.001
Performed 10-fold validation and scored 4.17% mean accuracy in graph classification


# AWE-DD

In [1]:
from AnonymousWalkEmbeddings import AWE

dataset = 'mutag'

batch_size = 100
window_size = 8
embedding_size_w = 128
embedding_size_d = 128
num_samples = 32

concat = False
loss_type = 'sampled_softmax'
optimize = 'Adagrad'
learning_rate = 1.0
root = 'Datasets/'
ext = 'graphml'
steps = 3
epochs = 1
batches_per_epoch = 50
candidate_func = None
graph_labels = None
awe = AWE(dataset = dataset, batch_size = batch_size, window_size = window_size,
                  embedding_size_w = embedding_size_w, embedding_size_d = embedding_size_d,
                  num_samples = num_samples, concat = concat, loss_type = loss_type,
                  optimize = optimize, learning_rate = learning_rate, root = root,
                  ext = ext, steps = steps, epochs = epochs, batches_per_epoch = batches_per_epoch,
                  candidate_func = candidate_func, graph_labels=graph_labels)

ModuleNotFoundError: No module named 'tensorflow'


CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


